name: Makefile CI

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  unit_tests:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: download love2d
      run: make download

    - name: run tests
      run: make test
